# Generated by Django 4.0.4 on 2022-04-24 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='books',
        ),
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='libraries.genre'),
        ),
    ]
