# Generated by Django 4.0.4 on 2022-04-24 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0004_remove_book_genres_book_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(blank=True, to='libraries.genre'),
        ),
    ]
