# Generated by Django 4.0.4 on 2022-04-24 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0005_alter_book_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='total_published',
        ),
        migrations.AddField(
            model_name='book',
            name='main_character',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='studio',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
