# Generated by Django 4.0.4 on 2022-04-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0006_remove_book_total_published_book_main_character_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='main_character',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='studio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
