# Generated by Django 4.0.4 on 2022-04-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0007_alter_book_main_character_alter_book_publisher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(blank=True, to='libraries.genre'),
        ),
        migrations.AddField(
            model_name='book',
            name='published',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
