# Generated by Django 4.0.4 on 2022-04-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0009_rename_genre_book_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='featured_image',
            field=models.ImageField(default='default.jpg', upload_to='book'),
        ),
    ]
