# Generated by Django 4.0.4 on 2022-05-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post_alter_profile_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='total_likes',
            field=models.IntegerField(default=0),
        ),
    ]
