# Generated by Django 4.0.4 on 2022-04-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(default='projects/default.jpg', upload_to='projects/'),
        ),
    ]
